
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'config/initializers/devise.rb'
    - 'config/environments/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true

Metrics/BlockLength:
  CountComments: false
  Max: 100
  Exclude:
    - 'app/admin/**/*.rb'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 30

